// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBibNQtTXtwG97147qoagy80LQWcj11fxU',
    appId: '1:112742949548:web:00f6089100ed8294697509',
    messagingSenderId: '112742949548',
    projectId: 'invoice-5f474',
    authDomain: 'invoice-5f474.firebaseapp.com',
    storageBucket: 'invoice-5f474.appspot.com',
    measurementId: 'G-BWKWKJ5BTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyRlf7AW515c6Apyw4i9Bdlfde_0hDFpo',
    appId: '1:112742949548:android:19da57c9697db0b1697509',
    messagingSenderId: '112742949548',
    projectId: 'invoice-5f474',
    storageBucket: 'invoice-5f474.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5SKtnfTIJvG_tAS1LnoQYLt9Nb4qdj2c',
    appId: '1:112742949548:ios:3f6dcf069bd975c9697509',
    messagingSenderId: '112742949548',
    projectId: 'invoice-5f474',
    storageBucket: 'invoice-5f474.appspot.com',
    iosBundleId: 'com.example.invoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5SKtnfTIJvG_tAS1LnoQYLt9Nb4qdj2c',
    appId: '1:112742949548:ios:3f6dcf069bd975c9697509',
    messagingSenderId: '112742949548',
    projectId: 'invoice-5f474',
    storageBucket: 'invoice-5f474.appspot.com',
    iosBundleId: 'com.example.invoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBibNQtTXtwG97147qoagy80LQWcj11fxU',
    appId: '1:112742949548:web:8ef3616466f6fc78697509',
    messagingSenderId: '112742949548',
    projectId: 'invoice-5f474',
    authDomain: 'invoice-5f474.firebaseapp.com',
    storageBucket: 'invoice-5f474.appspot.com',
    measurementId: 'G-09P90CW2ZD',
  );
}
